#!/usr/bin/env bash
set -euo pipefail
export AZURE_SUBSCRIPTION_ID="${AZURE_SUBSCRIPTION_ID}"
export INPUT_STAGE="${INPUT_STAGE}"
export LINUX_SCX_PASSWORD="${LINUX_SCX_PASSWORD}"
export LAB_AGENT_PAT="${LAB_AGENT_PAT}"
export LINUX_SCX_SSH_KEY="${LINUX_SCX_SSH_KEY}"
export ESTHER_VM_ADMIN_PASSWORD="${ESTHER_VM_ADMIN_PASSWORD}"
export INPUT_ROTATE_KEY="${INPUT_ROTATE_KEY}"
export LINUX_SCX_PPK_B64="${LINUX_SCX_PPK_B64}"
ENTRY_FAILED=0
echo "== step =="
export AZURE_SUBSCRIPTION_ID="${AZURE_SUBSCRIPTION_ID}"
export STAGE="${INPUT_STAGE}"
export LINUX_SCX_PASSWORD="${LINUX_SCX_PASSWORD}"
export LAB_AGENT_PAT="${LAB_AGENT_PAT}"
export LINUX_SCX_SSH_KEY="${LINUX_SCX_SSH_KEY}"
export GH_REPO="${GITHUB_REPOSITORY}"
export ESTHER_VM_ADMIN_PASSWORD="${ESTHER_VM_ADMIN_PASSWORD}"
export ROTATE_KEY="${INPUT_ROTATE_KEY}"
export LINUX_SCX_PPK_B64="${LINUX_SCX_PPK_B64}"
source scripts/lib/watchdog.sh 20 sweden
bash scripts/esther-sweden.sh
