name: ai-models-list
on: {workflow_dispatch: {}}
permissions: {contents: read}
jobs:
  run:
    uses: ./.github/workflows/_lab-job.yml
    secrets: inherit
    with:
      entry: ai-models-list__list
      timeout: 5
      azure_login: false
