name: Inspect Esther disk schema
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  run:
    uses: ./.github/workflows/_lab-job.yml
    secrets: inherit
    with:
      entry: esther-disk-schema__inspect
      timeout: 5
