name: esther-costs-read
on:
  workflow_dispatch:
  schedule:
    - cron: '40 4 * * *'
permissions:
  id-token: write
  contents: read
jobs:
  run:
    uses: ./.github/workflows/_lab-job.yml
    secrets: inherit
    with:
      entry: esther-costs-read__read
      timeout: 13
