name: esther-linux-create
on:
  workflow_dispatch:
    inputs:
      size: { type: string, default: Standard_B1s }
permissions:
  id-token: write
  contents: read
jobs:
  run:
    uses: ./.github/workflows/_lab-job.yml
    secrets: inherit
    with:
      entry: esther-linux-create__create
      timeout: 7
      extra_env: |
        INPUT_SIZE=${{ inputs.size }}
