name: Esther Speech F0 sample
on: {workflow_dispatch: {}}
permissions: {id-token: write, contents: read}
jobs:
  run:
    uses: ./.github/workflows/_lab-job.yml
    secrets: inherit
    with:
      entry: esther-speech-f0__sample
      timeout: 12
