name: esther-scom-phase1-dc
on:
  workflow_dispatch: {}
permissions:
  id-token: write
  contents: read
jobs:
  run:
    uses: ./.github/workflows/_lab-job.yml
    secrets: inherit
    with:
      entry: esther-scom-phase1-dc__dc
