name: esther-initial-password
on:
  workflow_dispatch:
    inputs:
      upn: { description: 'User UPN', required: true }
permissions: { id-token: write, contents: read }
jobs:
  run:
    uses: ./.github/workflows/_lab-job.yml
    secrets: inherit
    with:
      entry: esther-initial-password__set
      timeout: 5
      extra_env: |
        INPUT_UPN=${{ inputs.upn }}
