name: esther-dc-b1s
on:
  workflow_dispatch:
    inputs:
      stage: { type: choice, options: [read, resize-dc], default: read }
permissions: { id-token: write, contents: read }
jobs:
  run:
    uses: ./.github/workflows/_lab-job.yml
    secrets: inherit
    with:
      entry: esther-dc-b1s__run
      timeout: 7
      extra_env: |
        INPUT_STAGE=${{ inputs.stage }}
