name: release-cleanup
on: { workflow_dispatch: {} }
permissions: { contents: write }
jobs:
  run:
    uses: ./.github/workflows/_lab-job.yml
    secrets: inherit
    with:
      entry: release-cleanup__clean
      timeout: 5
      azure_login: false
