name: release-mega-check
on: { workflow_dispatch: {} }
permissions: { contents: read }
jobs:
  run:
    uses: ./.github/workflows/_lab-job.yml
    secrets: inherit
    with:
      entry: release-mega-check__check
      timeout: 5
      azure_login: false
